server:
  port: 5000
  servlet:
    context-path: /res


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://resourcemanager.csycq9etjnjx.us-east-1.rds.amazonaws.com:3306/resourcemanager?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Hello1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



#app_properties
key:
  jwtSecret: projectResourceSecretKey
  jwtExpiration: 86400000

#spring.datasource.url=jdbc:mysql://treehacks.csycq9etjnjx.us-east-1.rds.amazonaws.com:3306/keyboard
#spring.datasource.username=admin
#spring.datasource.password=Hello1234
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect